SHOW DATABASES;
DROP DATABASE IF EXISTS DOV;
CREATE DATABASE DOV;
USE DOV;

#DROP TABLE IF EXISTS OPTIONS;
#DROP TABLE IF EXISTS ORDERS;

CREATE TABLE OPTIONS(
	OPTION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OPTION_ADDRESS VARCHAR(42) NOT NULL,
	BASE_ASSET VARCHAR(10) NOT NULL,
    COLLATERAL_ASSET VARCHAR(10) NOT NULL,
    EXPIRY TIMESTAMP,
    SYMBOL VARCHAR(20),
    ROUND INT NOT NULL
);

CREATE TABLE ORDERS(
	ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OPTION_ID INT NOT NULL,
	SYMBOL VARCHAR(20),
    POSITION VARCHAR(10),
    STRIKE_PRICE VARCHAR(64),
    SETTLEMENT_PRICE VARCHAR(64),
    AMOUNT INT NOT NULL,
    PNL VARCHAR(64),
    ORDER_TIME TIMESTAMP,
    CLIENT_ADDRESS VARCHAR(42) NOT NULL,
    FOREIGN KEY(OPTION_ID) REFERENCES OPTIONS(OPTION_ID) ON DELETE CASCADE
);

CREATE TABLE STRIKES(
	STRIKE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OPTION_ID INT NOT NULL,
    STRIKE_PRICE VARCHAR(64),
    OPTION_PRICE VARCHAR(64),
    AVAILABLE_AMOUNT VARCHAR(64),
    STRIKE_INDEX INT NOT NULL,
    FOREIGN KEY(OPTION_ID) REFERENCES OPTIONS(OPTION_ID) ON DELETE CASCADE
);

#SELECT @@global.time_zone, @@session.time_zone, @@system_time_zone;


